USE [DESAFIOPRATICO]
GO

/****** Object:  Table [dbo].[Promocao]    Script Date: 08/03/2021 10:27:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Promocao](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](15) NOT NULL,
	[QTD_PORCAO] [int] NOT NULL,
	[QTD_PORCAO_PAGA] [int] NOT NULL,
	[DESCONTO] [numeric](8, 2) NOT NULL CONSTRAINT [DF_PROMOCAO_DESCONTO]  DEFAULT ((0)),
 CONSTRAINT [PK_PROMOCAO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


