USE [DESAFIOPRATICO]
GO

/****** Object:  Table [dbo].[Ingrediente]    Script Date: 08/03/2021 10:27:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Ingrediente](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](50) NOT NULL,
	[VALOR] [numeric](10, 2) NOT NULL CONSTRAINT [DF_INGREDIENTE_VALOR]  DEFAULT ((0)),
	[GRUPO] [varchar](10) NULL,
 CONSTRAINT [PK_INGREDIENTE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


