USE [DESAFIOPRATICO]
GO

/****** Object:  Table [dbo].[Cardapio_Ingrediente]    Script Date: 08/03/2021 10:27:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Cardapio_Ingrediente](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[INGREDIENTE_ID] [int] NOT NULL,
	[CARDAPIO_ID] [int] NOT NULL,
 CONSTRAINT [PK_CARDAPIO_INGREDIENTE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Cardapio_Ingrediente]  WITH CHECK ADD  CONSTRAINT [FK_CARDAPIO_INGREDIENTE_CARDAPIO] FOREIGN KEY([CARDAPIO_ID])
REFERENCES [dbo].[Cardapio] ([ID])
GO

ALTER TABLE [dbo].[Cardapio_Ingrediente] CHECK CONSTRAINT [FK_CARDAPIO_INGREDIENTE_CARDAPIO]
GO

ALTER TABLE [dbo].[Cardapio_Ingrediente]  WITH CHECK ADD  CONSTRAINT [FK_CARDAPIO_INGREDIENTE_INGREDIENTE] FOREIGN KEY([INGREDIENTE_ID])
REFERENCES [dbo].[Ingrediente] ([ID])
GO

ALTER TABLE [dbo].[Cardapio_Ingrediente] CHECK CONSTRAINT [FK_CARDAPIO_INGREDIENTE_INGREDIENTE]
GO


