USE [DESAFIOPRATICO]
GO

/****** Object:  Table [dbo].[Pedido_Item]    Script Date: 08/03/2021 10:27:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Pedido_Item](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PEDIDO_ID] [int] NOT NULL,
	[INGREDIENTE_ID] [int] NOT NULL,
 CONSTRAINT [PK_Pedido_Item] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Pedido_Item]  WITH CHECK ADD  CONSTRAINT [FK_Pedido_Item_Pedido] FOREIGN KEY([PEDIDO_ID])
REFERENCES [dbo].[Pedido] ([ID])
GO

ALTER TABLE [dbo].[Pedido_Item] CHECK CONSTRAINT [FK_Pedido_Item_Pedido]
GO


